import type { Download } from '@playwright/test';
import * as yaml from 'js-yaml';
import { expect, test } from '@fixtures/base';

async function readDownloadedFile(download: Download): Promise<string> {
    const fileBuffer = await download.createReadStream();
    const chunks: Buffer[] = [];

    for await (const chunk of fileBuffer) {
        chunks.push(Buffer.from(chunk as Uint8Array));
    }

    return Buffer.concat(chunks).toString('utf8');
}

async function readFixtureFile(filePath: string): Promise<string> {
    const fs = await import('fs/promises');
    return await fs.readFile(filePath, 'utf8');
}

function normalizeYamlContent(content: string): string {
    const sanitized = content.replace(/!<[^>]+>/g, '');

    const data = yaml.load(sanitized) as Record<string, unknown>;

    const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{1,3}Z$/;
    const NANOID_PATTERN = /^[A-Za-z0-9._-]+$/;

    function normalizeAutoGeneratedFields(obj: unknown): unknown {
        if (obj === null || typeof obj !== 'object') {
            return obj;
        }

        if (Array.isArray(obj)) {
            return obj.map(normalizeAutoGeneratedFields);
        }

        const normalized: Record<string, unknown> = {};

        for (const [key, value] of Object.entries(obj)) {
            if (key === 'created' || key === 'updated') {
                let dateString: string;

                if (value instanceof Date) {
                    dateString = value.toISOString();
                } else if (typeof value === 'string') {
                    dateString = value;
                } else {
                    throw new Error(
                        `${key} field is invalid. ` +
                            `Expected ISO date string or Date object, but got: ${JSON.stringify(value)} (type: ${typeof value})`
                    );
                }

                if (dateString.length > 0 && ISO_DATE_PATTERN.test(dateString)) {
                    normalized[key] = 'NORMALIZED_TIMESTAMP';
                } else {
                    throw new Error(`${key} field has invalid ISO date format: ${dateString}`);
                }
            } else if (key === 'id' || key === 'canvasId') {
                if (typeof value === 'string' && value.length > 0) {
                    expect(value).toMatch(NANOID_PATTERN);
                    normalized[key] = 'NORMALIZED_ID';
                } else {
                    throw new Error(
                        `${key} field is empty or invalid. ` +
                            `Expected non-empty nanoid string, but got: ${JSON.stringify(value)} (type: ${typeof value})`
                    );
                }
            } else {
                normalized[key] = normalizeAutoGeneratedFields(value);
            }
        }

        return normalized;
    }

    const normalized = normalizeAutoGeneratedFields(data);

    const yamlString = yaml.dump(normalized, {
        indent: 4,
        lineWidth: -1,
        noRefs: true
    });

    if (typeof yamlString !== 'string') {
        throw new Error('Failed to convert normalized data to YAML string');
    }

    return yamlString;
}

test.beforeEach('Open the Data Builder', async ({ ix }) => {
    await ix.studio.dataBuilder.overview.open();
});

test.describe('Data Builder', () => {
    test.describe('Data Models', () => {
        test.describe('Export after import from YAML file', () => {
            test(
                'should yield the same YAML file content',
                {
                    annotation: [
                        {
                            type: 'Discussion',
                            description:
                                'Amaury: Does this test actually make sense? Comparing YAML file content is unit testing, integration testing at best, but not e2e testing. Also, as the export schema changes, this test will break and require permanent maintenance (see evidence). Furthermore, it prevents us from running the test over again because it uses a fixed model name and technical name as static test data which creates a collision when running the test multiple times without explicit cleanup. This defeats the purpose of factories and is not in line with the rest of the playwright projects. Finally, the long normalizeYamlContent function is hard to understand and raises the question of what we are actually testing here if some specific yaml fields even need to be ignored from comparison.'
                        },
                        {
                            type: 'Evidence',
                            description:
                                'https://github.com/UnitedPlanet/data-builder/commits/dev/test/test-data/visitor.yaml'
                        }
                    ]
                },
                async ({ ix, factories }) => {
                    const filePath = 'test-data/visitor.yaml';
                    const testDataModel = factories.dataBuilder.models.createErDataModel({
                        name: 'bench-w0t1',
                        technicalName: 'bench-w0t1'
                    });

                    await ix.studio.dataBuilder.overview.dataModelsTab.importFromExport(
                        testDataModel,
                        filePath
                    );

                    await ix.studio.dataBuilder.workbench.exit();
                    await ix.studio.dataBuilder.overview.dataModelsTab.search(testDataModel.name);

                    const download =
                        await ix.studio.dataBuilder.overview.dataModelsTab.downloadExport(
                            testDataModel
                        );

                    const exportedContent = await readDownloadedFile(download);
                    const originalContent = await readFixtureFile(filePath);

                    const normalizedExported = normalizeYamlContent(exportedContent);
                    const normalizedOriginal = normalizeYamlContent(originalContent);

                    expect(normalizedExported).toBe(normalizedOriginal);
                }
            );
        });

        test.describe('Reimport an exported data model', () => {
            test('should yield a data model with the same entities and attributes', async ({
                ix,
                factories
            }) => {
                const testDataModel = factories.dataBuilder.models.createErDataModel();
                const testDataEntity = factories.dataBuilder.models.createDataModelEntity({
                    attributes: [
                        factories.dataBuilder.models.createDataEntityAttribute('char'),
                        factories.dataBuilder.models.createDataEntityAttribute('varchar'),
                        factories.dataBuilder.models.createDataEntityAttribute('text'),
                        factories.dataBuilder.models.createDataEntityAttribute('int16', {}),
                        factories.dataBuilder.models.createDataEntityAttribute('int32'),
                        factories.dataBuilder.models.createDataEntityAttribute('int64'),
                        factories.dataBuilder.models.createDataEntityAttribute('decimal'),
                        factories.dataBuilder.models.createDataEntityAttribute('real')
                    ]
                });

                await ix.studio.dataBuilder.overview.dataModelsTab.createErDataModel(testDataModel);
                await ix.studio.dataBuilder.workbench.explorer.dataExplorerTab.createEntity(
                    testDataEntity
                );

                await ix.studio.dataBuilder.workbench.exit();
                await ix.studio.dataBuilder.overview.dataModelsTab.search(testDataModel.name);

                const exportFile =
                    await ix.studio.dataBuilder.overview.dataModelsTab.downloadExport(
                        testDataModel
                    );

                const reimportedDataModel = factories.dataBuilder.models.createErDataModel();
                await ix.studio.dataBuilder.overview.dataModelsTab.importFromExport(
                    reimportedDataModel,
                    await exportFile.path()
                );

                await expect(
                    ix.studio.dataBuilder.workbench.canvas.entityCard(testDataEntity.technicalName)
                        .root
                ).toContainText(testDataEntity.name);
                for (const attribute of testDataEntity.attributes) {
                    await expect(
                        ix.studio.dataBuilder.workbench.canvas.entityCard(
                            testDataEntity.technicalName
                        ).root
                    ).toContainText(attribute.name);
                }
            });
        });

        test.describe('Import from OpenAPI specification', () => {
            test('should create a model with the correct REST requests', async ({
                ix,
                factories
            }) => {
                const filePath = 'test-data/fakeAPI 4.json';
                const testDataModel = factories.dataBuilder.models.createRestDataModel();

                await ix.studio.dataBuilder.overview.dataModelsTab.importFromOpenApi(
                    testDataModel,
                    filePath
                );

                await expect(ix.studio.notification('REST Model created')).toBeVisible();

                const entities = [
                    'Liste aller Produkte abrufen',
                    'Einzelnes Produkt abrufen',
                    'Benutzerliste abrufen',
                    'Einkaufswagen abrufen',
                    'Liste der Bestellungen abrufen',
                    'Neue Bestellung erstellen'
                ];
                for (const entity of entities) {
                    await expect(
                        ix.studio.dataBuilder.workbench.explorer.dataExplorerTab.dataEntityTreeItemLabel(
                            entity
                        )
                    ).toBeVisible();
                }

                await ix.studio.dataBuilder.workbench.explorer.dataExplorerTab.expandDataEntityTreeItem(
                    entities[0]
                );
                await expect(
                    ix.studio.dataBuilder.workbench.explorer.dataExplorerTab.dataEntityTreeItemLabel(
                        '/api/products 200 GET'
                    )
                ).toBeVisible();
            });
        });
    });
});
